slangwords_list = [
    "ababil:anak ingusan\n",
    "abal2:palsu\n",
    "abal:palsu\n",
    "abg:remaja\n",
    "ad:ada\n",
    "akooh:saya\n",
    "aje:saja\n",
    "alay:norak\n",
    "albm:album\n",
    "ampe:sampai\n",
    "anjir:waduh\n",
    "anyway:omong omong\n",
    "aq:saya\n",
    "asap:secepatnya\n",
    "ato:atau\n",
    "atw:atau\n",
    "ava:foto profil\n",
    "bacot:banyak bicara\n",
    "bangsat:kurang ajar\n",
    "baget:keras kepala\n",
    "baper:bawa perasaan\n",
    "bapuk:rusak\n",
    "bbrp:beberapa\n",
    "bcr:bicara\n",
    "bct:banyak bicara\n",
    "beb:sayang\n",
    "beberp:beberapa\n",
    "bebeb:pacar\n",
    "beberap:beberapa\n",
    "begin:awal\n",
    "bejibun:banyak\n",
    "bener:benar\n",
    "ber2:berdua\n",
    "ber3:bertiga\n",
    "better:lebih baik\n",
    "bf:pacar\n",
    "bgt:banget\n",
    "bgst:kurang ajar\n",
    "bgsat:kurang ajar\n",
    "bhas:bahas\n",
    "bhg:bahagia\n",
    "bikin:buat\n",
    "binggo:banget\n",
    "bingit:banget\n",
    "bklan:bakalan\n",
    "bkn:bukan\n",
    "blg:bilang\n",
    "blm:belum\n",
    "bnr:benar\n",
    "bngsat:kurang ajar\n",
    "bngst:kurang ajar\n",
    "bnyak:banyak\n",
    "bnyk:banyak\n",
    "br:baru\n",
    "brb:akan segera kembali\n",
    "brjaya:berjaya\n",
    "bs:bisa\n",
    "bsk:besok\n",
    "budeg:tidak mendengar\n",
    "budek:tuli\n",
    "cm:cuma\n",
    "cmiiw:koreksi saya\n",
    "cnt:cinta\n",
    "congrats:selamat\n",
    "crop:potong\n",
    "cya:sampai jumpa lagi\n",
    "da:ada\n",
    "dafuk:kurang ajar\n",
    "damat:tidak peduli\n",
    "dempa:demi apa\n",
    "dg:dengan\n",
    "dgn:dengan\n",
    "dkt:dekat\n",
    "dlm:dalam\n",
    "dlu:dulu\n",
    "dmn:di mana\n",
    "dpt:dapat\n",
    "dr:dari\n",
    "drpd:daripada\n",
    "dsna:disana\n",
    "dugem:dunia gemerlap\n",
    "elo:kamu\n",
    "elu:kamu\n",
    "emg:memang\n",
    "engga:tidak\n",
    "epsd:episode\n",
    "fake:palsu\n",
    "fans:penggemar\n",
    "faq:pertanyaan umum\n",
    "fham:paham\n",
    "fhm:paham\n",
    "fix:pasti\n",
    "ft:foto\n",
    "fyi:asal tahu saja\n",
    "gaada:tidak ada\n",
    "gabut:gaji buta\n",
    "gada:tidak ada\n",
    "gaje:tidak jelas\n",
    "gajebo:tidak jelas\n",
    "gajelas:tidak jelas\n",
    "gak:tidak\n",
    "galau:bimbang\n",
    "garing:hambar\n",
    "gatau:tidak tahu\n",
    "geje:tidak jelas\n",
    "gengges:ganggu\n",
    "geng:kelompok\n",
    "gf:pacar\n",
    "ggl:gagal\n",
    "gk:tidak\n",
    "gmn:bagaimana\n",
    "bgmn:bagaimana\n",
    "gmpng:mudah\n",
    "gogon:go internasional\n",
    "gokil:keren\n",
    "gpp:tidak apa-apa\n",
    "grammar:tata bahasa\n",
    "gt:gitu\n",
    "gue:saya\n",
    "gw:saya\n",
    "hacep:pesta pora\n",
    "hater:pembenci\n",
    "haters:pembenci\n",
    "hdp:hidup\n",
    "hdr:hadir\n",
    "hit:terpopuler\n",
    "hits:terkini\n",
    "hoaks:palsu\n",
    "hoax:palsu\n",
    "ig:instagram\n",
    "indo:indonesia\n",
    "iow:dengan kata lain\n",
    "ipon:iphone\n",
    "isue:isu\n",
    "jd:jadi\n",
    "jdi:jadi\n",
    "jdnya:jadinya\n",
    "jg:juga\n",
    "jgan:jangan\n",
    "jgn:jangan\n",
    "jk: jika\n",
    "jkw:jokowi\n",
    "jl:jalan\n",
    "jln:jalan\n",
    "jls:jelas\n",
    "jng:jangan\n",
    "jngn:jangan\n",
    "jutek:galak\n",
    "kamseupay:kampungan\n",
    "karn:karena\n",
    "kayak:seperti\n",
    "kayaknya:sepertinya\n",
    "kbr:kabar\n",
    "kca:kaca\n",
    "keknya:sepertinya\n",
    "keles:kali\n",
    "keleus:kali\n",
    "kepo:penasaran\n",
    "kgk:tidak\n",
    "kicep:diam\n",
    "kipak:bohong\n",
    "kk:kakak\n",
    "kl:kalau\n",
    "klo:kalau\n",
    "klon:duplikat\n",
    "klrg:keluarga\n",
    "klu:kalau\n",
    "km:kamu\n",
    "kmn:kemana\n",
    "kmrn:kemarin\n",
    "kn:kan\n",
    "knp:kenapa\n",
    "kongkow:kumpul kumpul\n",
    "kpd:kepada\n",
    "kpn:kapan\n",
    "krn:karena\n",
    "karna:karena\n",
    "krna:karena\n",
    "ktny:katanya\n",
    "kumkeb:kumpul kebo\n",
    "kyk:seperti\n",
    "kzl:kesal\n",
    "lebay:berlebihan\n",
    "lebeh:berlebihan\n",
    "lg:lagi\n",
    "lgs:langsung\n",
    "lagsg:langsung\n",
    "lgsg:langsung\n",
    "lgsug:langsung\n",
    "liat:lihat\n",
    "lht:lihat\n",
    "lnjut:lanjut\n",
    "lo:kamu\n",
    "loe:kamu\n",
    "lol:tertawa\n",
    "love:cinta\n",
    "lu:kamu\n",
    "lwt:lewat\n",
    "maaci:terima kasih\n",
    "maap:maaf\n",
    "mabok:mabuk\n",
    "mager:malas gerak\n",
    "maharani:mahal\n",
    "maho:homoseksual\n",
    "mainstream:sangat umum\n",
    "males:malas\n",
    "manggil:panggil\n",
    "mantab:mantap\n",
    "mantap:mantap\n",
    "maslah:masalah\n",
    "mcm:macam\n",
    "mcem:macam\n",
    "mehong:mahal\n",
    "meneketehe:tidak tahu\n",
    "menel:centil\n",
    "mgkn:mungkin\n",
    "mimin:admin\n",
    "minn:admin\n",
    "mkn:makan\n",
    "mksd:maksud\n",
    "mksh:terima kasih\n",
    "mlm:malam\n",
    "mls:malas\n",
    "mmg:memang\n",
    "mntap:hebat\n",
    "mntp:hebat\n",
    "mo:mau\n",
    "modus:maksud lain\n",
    "mrk:mereka\n",
    "mrka:mereka\n",
    "msh:masih\n",
    "mslh:masalah\n",
    "msalah:masalah\n",
    "mslah:masalah\n",
    "msalh:masalah\n",
    "much:lebih\n",
    "mure:murah\n",
    "mw:mau\n",
    "ngapa:mengapa\n",
    "ngeh:paham\n",
    "ngeuh:paham\n",
    "nggak:tidak\n",
    "nggu:menunggu\n",
    "ngk:tidak\n",
    "ngmng:omong\n",
    "ngomng:omong\n",
    "ngomong:omong\n",
    "ngotot:paksa\n",
    "ntap:mantap\n",
    "nic:penggemar agnezmo\n",
    "nice:bagus\n",
    "nicong:penggemar agnezmo\n",
    "nmr:nomor\n",
    "nntn:nonton\n",
    "nongkrong:kumpul-kumpul\n",
    "ntn:nonton\n",
    "nunggu:menunggu\n",
    "nyungsep:jatuh\n",
    "official:resmi\n",
    "olh:oleh\n",
    "or:atau\n",
    "org:orang\n",
    "pake:pakai\n",
    "palbis:paling bisa\n",
    "parte:partai\n",
    "pcr:pacar\n",
    "pcran:pacaran\n",
    "pd:pada\n",
    "pdhal:padahal\n",
    "pdhl:padahal\n",
    "peres:palsu\n",
    "pg:pagi\n",
    "pgg:pegang\n",
    "php:pembohong\n",
    "pinter:pintar\n",
    "pk:pakai\n",
    "pke:pakai\n",
    "plg:pulang\n",
    "pls:tolong\n",
    "pnh:pernah\n",
    "pntg:penting\n",
    "pny:punya\n",
    "prasmul:perasaan saja\n",
    "prcya:percaya\n",
    "prnh:pernah\n",
    "pst:pesat\n",
    "recokin:ganggu\n",
    "rempong:repot\n",
    "ri:republik indonesia\n",
    "rotfl:tertawa\n",
    "sabeb:bebas\n",
    "sbg:sebagai\n",
    "sc:tangkapan layar\n",
    "ss:tangkapan layar\n",
    "schedule:jadwal\n",
    "sdh:sudah\n",
    "selow:santai\n",
    "sgt:sangat\n",
    "sgtu:segitu\n",
    "sgtuny:segitunya\n",
    "sj:saja\n",
    "sjjurny:sejujurnya\n",
    "skali:sekali\n",
    "skrg:sekarang\n",
    "now:sekarang\n",
    "slh:salah\n",
    "sll:selalu\n",
    "sm:sama\n",
    "smg:semoga\n",
    "smga:semoga\n",
    "smp:sampai\n",
    "smw:semua\n",
    "smwnya:semuanya\n",
    "sperti:seperti\n",
    "sprti:seperti\n",
    "spy:supaya\n",
    "ss:cuplikan layar\n",
    "stage:panggung\n",
    "stj:setuju\n",
    "stuju:setuju\n",
    "sy:saya\n",
    "sya:saya\n",
    "syg:sayang\n",
    "tak:mau\n",
    "tau:tahu\n",
    "td:tadi\n",
    "tdk:tidak\n",
    "th:tahun\n",
    "thn:tahun\n",
    "tengsin:malu\n",
    "thn:tahun\n",
    "tkt:takut\n",
    "tkut:takut\n",
    "tp:tapi\n",
    "tpii:tapi\n",
    "trs:terus\n",
    "trus:terus\n",
    "ttg:tentang\n",
    "ttp:tetap\n",
    "tw:tahu\n",
    "typo:salah tulis\n",
    "uda:sudah\n",
    "udh:sudah\n",
    "unyu:menggemaskan\n",
    "uteg:otak\n",
    "vs:melawan\n",
    "with:dengan\n",
    "woles:santai\n",
    "wtf:apa\n",
    "x:kali\n",
    "y:ya\n",
    "yahc:yah\n",
    "ye:ya\n",
    "yg:yang\n",
    "undah:undang\n",
    "max:maksimal\n",
    "stop:berhenti\n",
    "stoplah:berhenti\n",
    "setop:berhenti\n",
    "head:kepala\n",
    "wes:udah\n",
    "dadi:jadi\n",
    "panjenengan:anda\n",
    "sudi:rela\n",
    "ora:tidak\n",
    "pakde:bapak\n",
    "pakdhe:bapak\n",
    "bpk:bapak\n",
    "bapakk:bapak\n",
    "gantino:gantinya\n",
    "ptovokasi:provokasi\n",
    "provokssi:provokasi\n",
    # "uu:undang undang\n",
    # "uud:undang undang dasar\n",
    "dijadiin:dijadikan\n",
    "bacod:banyak bicara\n",
    "goreng:bahas\n",
    "kiro:kira\n",
    "engkok:nanti\n",
    "sopo:siapa\n",
    "ojolali:jangan lupa\n",
    "nyuwon:meminta\n",
    "ambek:marah\n",
    "lord:tuan\n",
    "tuk:untuk\n",
    "rojo:raja\n",
    "waline:walinya\n",
    "perpanjmg:perpanjang\n",
    "penundaana:penundaan\n",
    "penumdaan:penundaan\n",
    "mestibya:mestinya\n",
    "zulkifly:zulkifli\n",
    "saiki:sekarang\n",
    "nti:nanti\n",
    "tst:tersebut\n",
    "tsb:tersebut\n",
    "issue:isu\n",
    "issu:isu\n",
    "masukin:masukan\n",
    "prengkap:perangkap\n",
    "digoreng:dibahas\n",
    "mestibya:mestinya\n",
    "adlh:adalah\n",
    "adlah:adalah\n",
    "you:anda\n",
    "sono:sana\n",
    "pelakyou:pelaku\n",
    "umik:bicara\n",
    "fik:pasti\n",
    "nyapres:mencalonkan presiden\n",
    "predisen:presiden\n",
    "ngerti:paham\n",
    "group:kelompok\n",
    "waras:sehat\n",
    "want:mau\n",
    "you:anda\n",
    "know:tahu\n",
    "tidakngiler:tidak nafsu\n",
    # "gonggong:bersuara\n",
    "mmang:memang\n",
    "bolot:tidak dengar\n",
    "hrs:harus\n",
    "statement:pernyataan\n",
    "statemen:pernyataan\n",
    "stetment:pernyataan\n",
    "berulangkali:beberapa kali\n",
    "berulang:beberapa\n",
    "yth:yang terhormat\n",
    "area:wilayah\n",
    "trending:berita hangat\n",
    "ketidak:tidak\n",
    "setujuannya:setuju\n",
    "porak:rusak\n",
    "hy:hanya\n",
    "setback:kemunduran\n",
    "sgr:segera\n",
    "reasoneble:pantas\n",
    "masyarakt:masyarakat\n",
    "blunder:keliru\n",
    "cilik:kecil\n",
    "ngerasa:merasa\n",
    # "seantero:seluruh\n",
    "amsyong:musibah\n",
    "tepis:tolak\n",
    "menepis:menolak\n",
    "menolaj:tolak\n",
    "blng:bilang\n",
    "framing:memandang\n",
    "riuh:berisik\n",
    "king:raja\n",
    "champion:pemenang\n",
    "lip:bibir\n",
    "service:layanan\n",
    "crisis:krisis\n",
    "response:respons\n",
    "menyalahkab:menyalahkan\n",
    "bego:bodoh\n",
    "begonya:bodoh\n",
    "subtansial:sesungguhnya\n",
    "gembar:berteriak\n",
    "super:hebat\n",
    "lgsung:langsung\n",
    "tidk:tidak\n",
    "percayaan:percaya\n",
    "musti:mesti\n",
    "kepilih:terpilih\n",
    "milih:pilih\n",
    "plus:tambah\n",
    "guhe:saya\n",
    "nalas:nalar\n",
    # "bohir:pemilik modal\n",
    # "bohirkah:pemilik modal\n",
    "tgas:tegas\n",
    "mmbenci:membenci\n",
    "mnjatuhkan:menjatuhkan\n",
    "adl:adalah\n",
    "nggiring:giring\n",
    "sensitifitas:sensitivitas\n",
    "tehnik:teknik\n",
    "ributin:meributkan\n",
    "mengatasnamakan:memakai nama\n",
    "faham:paham\n",
    "adek:adik\n",
    "stlh:setelah\n",
    "ngasih:kasih\n",
    "clear:jelas\n",
    # "con:konferensi\n",
    "becus:mampu\n",
    "ngurus:mengurus\n",
    "perikde:periode\n",
    "ngelarang:melarang\n",
    "showone:pergi\n",
    "kalo:kalau\n",
    "blak:terbuka\n",
    # "mengasongkan:menjijikan\n",
    # "memfabrikasi:membuat\n",
    "skrisut:tangkapan layar\n",
    "screenshot:tangkapan layar\n",
    "ngomongin:membicarakan\n",
    "postingan:unggahan\n",
    "kekacaun:kekacauan\n",
    "ditabok:dipukul\n",
    "digebukin:dipukul\n",
    "copot:lepas\n",
    "dng:dengan\n",
    "mreka:mereka\n",
    "tegasan:tegas\n",
    "capek:lelah\n",
    "missi:misi\n",
    "kebelet:tidak tahan\n",
    "pengen:ingin\n",
    "mengungumkan:mengumumkan\n",
    "pebruari:februari\n",
    "nurunin:menurunkan\n",
    "testing:pengujian\n",
    "water:air\n",
    "tunjukkn:tunjukan\n",
    "waja:wajah\n",
    "menunjukkn:menunjukan\n",
    "trjadi:terjadi\n",
    "update:memperbarui\n",
    "channel:saluran\n",
    # "prof:professor\n",
    "mentri:menteri\n",
    "azas:asas\n",
    "alloh:allah\n",
    # "budek:tidak dapat mendengar\n",
    # "tuli:tidak dapat mendengar\n",
    "mhsw:mahasiswa\n",
    "berargument:berargumen\n",
    "tgl:tanggal\n",
    "seorg:seorang\n",
    "mrnunda:menunda\n",
    "oligakri:oligarki\n",
    "jga:juga\n",
    "dri:dari\n",
    "biarpun:meskipun\n",
    "sampe:sampai\n",
    "kemaren:kemarin\n",
    "dirubah:diubah\n",
    "ekslasi:eskalasi\n",
    "culas:curang\n",
    "berhoax:berbohong\n",
    "prilaku:perilaku\n",
    "buosokkkkk:busuk\n",
    "spt:seperti\n",
    "nuntut:tuntut\n",
    "berterimaksih:berterima kasih\n",
    "disupport:didukung\n",
    "jadual:jadwal\n",
    "kau:anda\n",
    "gerombolan:kelompok\n",
    "bacotttt:banyak bicara\n",
    "semagat:semangat \n",
    "kpnstitusi:konstitusi\n",
    "dilaksakan:dilaksanakan\n",
    "ksh:kasih\n",
    "kedah:terbuka lebar\n",
    "cekap:efisien\n",
    # "cukong:pengusaha besar\n",
    "denger:dengar\n",
    "ngga:tidak\n",
    "waktuny:waktunya\n",
    "aktifitas:aktivitas\n",
    "dn:dan\n",
    "kepla:kepala\n",
    "mang:memang\n",
    "nanya:tanya\n",
    "ngarep:berharap\n",
    "paniiiik:panik\n",
    "klean:kalian\n",
    "ngmong:bicara\n",
    "sound:suara\n",
    "nyalahin:menyalahkan\n",
    "dipake:dipakai\n",
    "resufle:perombakan\n",
    "gampang:mudah\n",
    "grgr:gara gara\n",
    # "gegara:masalah\n",
    "nggk:tidak\n",
    "cmn:cuman\n",
    "mak:maksimal\n",
    "nolak:tolak\n",
    "digiring:didorong\n",
    "wkt:waktu\n",
    "sblm:sebelum\n",
    "puyeng:pusing\n",
    "tetep:tetap\n",
    "skg:sekarang\n",
    "mewacakan:mewacanakan\n",
    "ngurusi:mengurus\n",
    "ngurus:mengurus\n",
    "sangsi:sanksi\n",
    "dmna:di mana\n",
    # "mengegolkan:memperjuangkan\n",
    "mhs:mahasiswa\n",
    "ngajak:mengajak\n",
    "jengkelin:menjengkelkan\n",
    "nyebelin:menyebalkan\n",
    "bnget:banget\n",
    "temen:teman\n",
    "univ:universitas\n",
    "buatin:buatkan\n",
    "pekok:bodoh\n",
    "pingin:ingin\n",
    "kagak:tidak\n",
    "sebenernya:sebenarnya\n",
    "sbnrnya:sebenarnya\n",
    "gaes:kawan\n",
    "bestiee:sahabat\n",
    "medsos:media sosial\n",
    "reward:hadiah\n",
    "ketok:ketuk\n",
    "jlnan:jalanan\n",
    "rakyatmarah:rakyat marah\n",
    "kere:miskin\n",
    "cc:teruskan\n",
    "numpas:tumpas\n",
    "sepedah:sepeda\n",
    "gile:gila\n",
    "reposted:diunggah lagi\n",
    "inget:ingat\n",
    "dipiara:dipelihara\n",
    "trunanya:pemudanya\n",
    "ssuikn:sesuaikan\n",
    "bgitu:begitu\n",
    "ntar:nanti\n",
    "merubah:mengubah\n",
    "bacotan:pembicaraan\n",
    "ngumpet:bersembunyi\n",
    "nyabu:memakai sabu\n",
    "brow:kawan\n",
    "gimana:bagaimana\n",
    "subtansi:substansi\n",
    "online:daring\n",
    "news:berita\n",
    "no:tidak\n",
    "teriakan:teriak\n",
    # "kroco:anak buah\n",
    "emang:memang\n",
    "jbtn:jabatan\n",
    "nasbung:nasi bungkus\n",
    "survey:survei\n",
    "merubah:mengubah\n",
    "nasehat:nasihat\n",
    "slalu:selalu\n",
    "mnjalankan:menjalankan\n",
    "rformasi:reformasi\n",
    "isyu:isu\n",
    # "jaran:kuda\n",
    # "sewidak:enam puluh\n",
    "hnya:hanya\n",
    "hny:hanya\n",
    "birahi:berahi\n",
    "bhw:bahwa\n",
    "bloon:bodoh\n",
    "nyuruh:menyuruh\n",
    "ngibul:membohongi\n",
    # "onar:gaduh\n",
    "mbikin:membuat\n",
    "lengserin:lengser\n",
    "naikin:menaikan\n",
    "bro:kawan\n",
    "panteslah:pantaslah\n",
    "untk:untuk\n",
    "ngelanggar:melanggar\n",
    "saranya:sarannya\n",
    "knapa:kenapa\n",
    "sprtnya:sepertinya\n",
    "bonceng:ikut\n",
    "mamak:ibu\n",
    "biang kerok:pembuat gaduh\n",
    "gaess:kawan\n",
    "nurut:patuh\n",
    "ballon:balon\n",
    "berjln:berjalan\n",
    "blusukan:masuk\n",
    "cover both side:berimbang tidak memihak\n",
    "thd:terhadap\n",
    "ngebandingin:membandingkan\n",
    # "gub:gubernur\n",
    "unfaedah:tidak berguna\n",
    "never:tidak pernah\n",
    "dodo:widodo\n",
    "periodelagi:periode lagi\n",
    "priode:periode\n",
    "mrpkan:merupakan\n",
    "gorengan:bahasan\n",
    "recovery:penyembuhan\n",
    "nampaknya:tampaknya\n",
    "all:semua\n",
    "btw:omong omong\n",
    "kebalik:terbalik\n",
    "tetiba:tiba tiba\n",
    "hai:halo\n",
    "hapenya:ponselnya\n",
    "hp:ponsel\n",
    "mndukung:mendukung\n",
    "berpolimik:berpolemik\n",
    "ngebet:ingin sekali\n",
    "menggoreng:membahas\n",
    "mengoreng:membahas\n",
    "kuyo:hina\n",
    "mhimbau:menghimbau\n",
    "ngomongnya:bicaranya\n",
    "ga:tidak\n",
    # "langgeng:abadi\n",
    # "juntrungnya:pendirian\n",
    "cuan:uang\n",
    "knpa:kenapa\n",
    "songong:sombong\n",
    "arogan:sombong\n",
    "bu:ibu\n",
    "yng:yang\n",
    "sampa:sampai\n",
    "ahir:akhir\n",
    "mecat:pecat\n",
    "seharus:seharusnya\n",
    "pnundaan:penundaan\n",
    "nonton:tonton\n",
    "jidat:dahi\n",
    "lgi:lagi\n",
    "melontrakan:melontarkan\n",
    "rill:nyata\n",
    "sangsinya:sanksinya\n",
    "plonga plongo:terkejut\n",
    "gampang:mudah\n",
    "kucau:kacau\n",
    "gamau:tidak mau\n",
    "turunin:turunkan\n",
    "intrik:kabar bohong\n",
    "nyinyirin:nyinyir\n",
    "dinjamin:dijamin\n",
    "triliyun:triliun\n",
    "chaos:kacau\n",
    "orovokasi:provokasi\n",
    "guys:kawan\n",
    "hoak:palsu\n",
    "geloran:gelora\n",
    "kian:semakin\n",
    "editor:pennyunting\n",
    "adlh:adalah\n",
    "pemr:pemerintah\n",
    # "amburadul:berantakan\n",
    "greedy:tamak\n",
    # "gedek:kesal\n",
    "mknya:makanya\n",
    # "multitafsir:banyak makna\n",
    # "jokpro:pendukung jokowi\n",
    # "hartartoo:hartarto\n",
    "mangkanya:makanya\n",
    # "agitasi:hasutan\n",
    "ngomongan:omong\n",
    "ngaco:kacau\n",
    "power:kuasa\n",
    "drunken:mabuk\n",
    "gimmick:menarik hati\n",
    "kebo:kerbau\n",
    "new:baru\n",
    # "post:unggah\n",
    # "klik:tekan\n",
    # "doyan:suka\n",
    "know:tahu\n",
    "nothing:tidak ada\n",
    "about:tentang\n",
    "politics:politik\n",
    "eyes:mata\n",
    # "bandit:penjahat\n",
    "bandits:penjahat\n",
    "kawanbinnya:kawan binaannya\n",
    "mjd:menjadi\n",
    # "cucok:cakap\n",
    # "ngoyo:maksa diri\n",
    "syahwat:nafsu\n",
    "justivikasi:pembenaran\n",
    "isuenya:isunya\n",
    # "greget:semangat\n",
    "masyarakatpun:masyarakat pun\n",
    "kontinyu:berlanjut\n",
    # "negarawan:ahli negara\n",
    "kagak:tidak\n",
    "golkan:menyukseskan\n",
    "nekat:berani\n",
    "mencopot:melepas\n",
    # "getol:rajin\n",
    # "quo:kemana\n",
    # "vadis:pergi\n",
    "etung:hitung\n",
    "sampean:anda\n",
    "dipake:dipakai\n",
    "respek:hormat\n",
    "maluin:malu\n",
    "dek:adik\n",
    "penasaran:ingin tahu\n",
    "geger:gempar\n",
    "gedhen:besar sekali\n",
    "ptuh:patuh\n",
    "pda:pada\n",
    "sipesek:si pesek\n",
    "nyalon:mencalonkan\n",
    "managing:manajemen\n",
    "director:direktur\n",
    # "bolot:tidak dengar\n",
    "laporin:laporkan\n",
    "kmdn:kemudian\n",
    "mrpkn:merupakan\n",
    "thdp:terhadap\n",
    "alus:halus\n",
    "sdgkn:sedangkan\n",
    "sdgkan:sedangkan\n",
    "simpulin:simpulkan\n",
    "install:pasang\n",
    "sepertiku:seperti saya\n",
    "hrsnya:harusnya\n",
    "menurutku:menurut saya\n",
    "ndak:tidak\n",
    "biar:agar\n",
    "mencolok:terlihat jelas\n",
    "bro:kawan\n",
    "ikutin:ikuti\n",
    "pointny:intinya\n",
    "point:inti\n",
    # "tengok:lihat\n",
    "jikowi:jokowi\n",
    "sdg:sedang\n",
    "dimungkiri:dibantah\n",
    "omnifora:omnivora\n",
    "kmbali:kembali\n",
    "mngusulkan:mengusulkan\n",
    "mnyerang:menyerang\n",
    "masiv:masif\n",
    "diflintir:dipelintir\n",
    "terdekatny:terdekatnya\n",
    "enggan:tidak mau\n",
    "element:elemen\n",
    "simpel:sederhana\n",
    "dara:darah\n",
    "meloby:bernegosiasi\n",
    "bgm:bagaimana\n",
    "berubah:ubah\n",
    "ngubah:ubah\n",
    "ngaku:mengaku\n",
    "repormasi:reformasi\n",
    "antek:kelompok\n",
    # "konslet:rusak\n",
    "napah:kenapa\n",
    "taunya:tahunya\n",
    "diamadem:diamandemen\n",
    "mengaman:aman\n",
    "bapa:bapak\n",
    # "gentle:sopan\n",
    "wani:berani\n",
    "ndobol:bohong\n",
    "alesan:alasan\n",
    "ktika:ketika\n",
    "salamm:salam\n",
    "impich:mimpi\n",
    "korbankn:korbankan\n",
    "perpanjanggan:perpanjangan\n",
    "perpanjangaan:perpanjangan\n",
    "perpanjamg:perpanjangan\n",
    "ngejeplak:menjiplak\n",
    "nyalahi:menyalahi\n",
    "preiode:periode\n",
    "menghianati:mengkhianati\n",
    "prihatin:khawatir\n",
    "maen:main\n",
    "pekaes:pks\n",
    "jowoki:jokowi\n",
    "unt:untuk\n",
    "deal:sepakat\n",
    "emaknya:ibu\n",
    "entar:nanti\n",
    "penghianat:pengkhianat\n",
    "kelojot:kejang\n",
    "buktiin:buktikan\n",
    "silahkan:silakan\n",
    "sekedar:sekadar\n",
    "analisa:analisis\n",
    "praktek:praktik\n",
    "resiko:risiko\n",
    "firnah:fitnah\n",
    "mnyatakan:menyatakan\n",
    "diomongin:dibicarakan\n",
    "sharing:berbagi\n",
    "share:bagi\n",
    # "caper:cari hati\n",
    "motone:mata\n",
    "picek:rusak\n",
    # "pres:presiden\n",
    # "purn:purnawirawan\n",
    "tpi:tapi\n",
    # "pro:dukung\n",
    "fair:adil\n",
    "meloka:menolak\n",
    "menolak:tolak\n",
    "mnyampaikan:menyampaikan\n",
    # "menjegal:menjatuhkan\n",
    "terimakasih:terima kasih\n",
    "hng:hingga\n",
    "melintir:tergulung\n",
    "jujurly:sejujurnya\n",
    "menjajnjikan:menjanjikan\n",
    "dlan:lebih dulu\n",
    "masyarak:masyarakat\n",
    "comberan:air kotor\n",
    "circle:lingkaran\n",
    "shg:sehingga\n",
    "ayahnya:ayah\n",
    "koar:teriak\n",
    "diapain:apa\n",
    # "jorok:kotor\n",
    # "background:latar belakang\n",
    "kuping:telinga\n",
    "design:desain\n",
    "perbanjangan:perpanjangan\n",
    "prpanjangan:perpanjangan\n",
    "mmnuhi:memenuhi\n",
    # "kroni:kawan\n",
    # "kab:kabupaten\n",
    # "prov:provinsi\n",
    "mikirnya:pikirnya\n",
    # "langgam:model\n",
    "menggolkan:menyukseskan\n",
    "kmren:kemarin\n",
    "turunany:turunannya\n",
    "brlebihan:berlebihan\n",
    "ssuaikn:sesuaikan\n",
    "ngeributin:meributkan\n",
    "big:besar\n",
    # "dusta:bohong\n",
    "kebebesan:kebebasan\n",
    "prlu:perlu\n",
    "dpertahankn:dipertahankan\n",
    "mendiamkan:diam\n",
    # "mending:lebih baik\n",
    "mempertanyakn:mempertanyakan \n",
    "drun:kadrun \n",
    "kdrun:kadrun \n",
    "kadron:kadrun \n",
    "toak:tolak \n",
    "jadul:lama \n",
    # "hacker:peretas \n",
    "ir:insinyur\n",
    "link:tautan\n",
    "gamblang:jelas\n",
    "lengser:turun\n",
    "gara:karena\n",
    "gencar:terus\n",
    # "buzzerrp:buzzer\n",
    # "buzer:buzzer\n",
    # "harto:suharto\n",
    "wajahh:wajah\n",
    "mengerti:paham\n",
    "maksa:paksa\n",
    "ngeyel:keras kepala\n",
    "hrga:harga\n",
    "takutny:takutnya\n",
    "menjawb:menjawab\n",
    "ceritane:cerita\n",
    "tivi:tv\n",
    "setres:stres\n",
    "pundasi:pondasi\n",
    "gerakan:gerak\n",
    "goblok:bodoh\n",
    "waee:saja\n",
    "selamtin:selamatkan\n",
    "ngomel:marah\n",
    "evalusai:evaluasi\n",
    "dtng:datang\n",
    "supporternya:pendukungnya\n",
    "msa:masa\n",
    "iy:ya\n",
    "oiya:oh ya\n",
    "ticketing:beli tiket\n",
    "goblok:bodoh\n",
    "goblk:bodoh\n",
    "academy:akademi\n",
    "kowe:kamu\n",
    "mboten:tidak\n",
    "den:raden\n",
    "tv:televisi\n",
    "insert:memasukan\n",
    "that:itu\n",
    "ancene:betulkah\n",
    "senenagane:kesenangan\n",
    "dagel:lucu\n",
    "koen:kamu\n",
    "bosok:busuk\n",
    "kabeh:semua\n",
    "koe:kamu\n",
    "aja:jangan\n",
    "bego:bodoh\n",
    "aj:aja\n",
    "tdk:tidak\n",
    "ancuur:hancur\n",
    "gak:tidak\n",
    "koyok:seperti\n",
    "ngene:ini\n",
    "nak:di\n",
    "ae:aja\n",
    "nggak:tidak\n",
    "hang:yang\n",
    "pie:bagaimana\n",
    "jane:katanya\n",
    "gue:saya\n",
    "gt:gitu\n",
    "tp:tapi\n",
    "keknya:sepertinya\n",
    "tenan:banget\n",
    "utk:untuk\n",
    "cmn:hanya\n",
    "gede:besar\n",
    "mulu:terus\n",
    "ama:sama\n",
    "sobat:sahabat\n",
    "ambyar:bercerai berai\n",
    "min:admin\n",
    "bungkam:tutup mulut\n",
    "yg:yang\n",
    "min:admin\n",
    "flare-smoke bomb:bom asap api\n",
    "momok:takut\n",
    "inspeksi:pemeriksaan\n",
    "sumbu:benang\n",
    "maenya:mainnya\n",
    "mngp:menganggap\n",
    "respons:tanggapan\n",
    "fairplay:bermain adil\n",
    "iso:bisa\n",
    "ra:tidak\n",
    "emng:emang\n",
    "sndri:sendiri\n",
    "nunggak:terhambat\n",
    "pesik:pesik kediri\n",
    "coach:pelatih\n",
    "ngeles:alasan\n",
    "dsr:dasar\n",
    "duwe:punya\n",
    "klau:kalau\n",
    "positive thingking:berpikir positif\n",
    "jerat:kena\n",
    "minus:dikurangi\n",
    "skema:bagan\n",
    "high pressing direct football:sepak bola langsung dengan tekanan tinggi\n",
    "fighting spirit:semangat bertarung\n",
    "geunah:berhasil\n",
    "ayaan:ada\n",
    "nu:yang\n",
    "nyuarakeun:menyuarakan\n",
    "jajaheun:jajahan\n",
    "jeung:sama\n",
    "sold:habis\n",
    "seng:yang\n",
    "do:sampai\n",
    "ben:supaya\n",
    "entuk:habis\n",
    "neng:kapan\n",
    "ngulama:ulama\n",
    "you:kamu\n",
    "ny:nya\n",
    "bnyk:banyak\n",
    "gmna:bagaimana\n",
    "wat:untuk\n",
    "club:klub\n",
    "diem:diam\n",
    "kocak:lucu\n",
    "gpernah:belum pernah\n",
    "puas:gembira\n",
    "nton:nonton\n",
    "scandal:memalukan\n",
    "viral:menyebar luas\n",
    "bnyk:banyak\n",
    "wat:untuk\n",
    "gbsa:engga bisa\n",
    "initu:ini\n",
    "mbok ben:bisa gitu\n",
    "satusewu:seratus ribu\n",
    "ki:semua\n",
    "blogh:bodoh\n",
    "play:bermain\n",
    "tanding:berlawanan\n",
    "menangin:menang\n",
    "sty:shin tae yong\n",
    "layak:pantas\n",
    "sengit:dahsyat\n",
    "tc:pusat pelatihan\n",
    "genks:sahabat\n",
    "ssb:sekolah sepakbola\n",
    "pasrah:menyerahkan\n",
    "event:kegiatan\n",
    "kab:kabupaten\n",
    "kerawat:pelihara\n",
    "taun:tahun\n",
    "lugu:banyak tingkah\n",
    "bray:sahabat\n",
    "hepi:senang\n",
    "rugi:menderita\n",
    "join:gabung\n",
    "enggement:perjanjian\n",
    "relate:sesuai\n",
    "wajar:biasa\n",
    "krja:kerja\n",
    "heran:bingung\n",
    "mending:dari pada\n",
    "sports:olahraga\n",
    "pattynama:shayne pattynama\n",
    "krl:kereta rel listrik\n",
    "masak:masa\n",
    "ribet:susah\n",
    "kabare:kabarnya\n",
    "motif:pola\n",
    "alias:sama dengan\n",
    "giat:rajin\n",
    "problem:masalah\n",
    "sertif:sertifikat\n",
    "ngapunten:maaf\n",
    "mgkin:mungkin\n",
    "it:itu\n",
    "booking:pesan\n",
    "and:dan\n",
    "pildun:piala dunia\n",
    "call:menelpon\n",
    "ndan:dan\n",
    "publik:umum\n",
    "private:pribadi\n",
    "infrastruktur:prasarana\n",
    "kudu:harus\n",
    "fun:senang\n",
    "football:sepak bola\n",
    "diem:diam\n",
    "venue:tempat\n",
    "udh:udah\n",
    "caper:cari perhatian\n",
    "ben:supaya\n",
    "entok:habis\n",
    "ente:kamu\n",
    "aliss:sama dengan\n",
    "norakkkk:heran\n",
    "cringe:malu\n",
    "good:semoga\n",
    "luck:sukses\n",
    "teu:engga\n",
    "ceunah:kata nya\n",
    "selamatkeun:selamatkan\n",
    "gembos:kosong\n",
    "refrensi:petunjuk\n",
    "kaya:seperti\n",
    "scouting:kepanduan\n",
    "sk:surat keputusan\n",
    "inti:utama\n",
    "working:kerja\n",
    "class:kelas\n",
    "adala:adalah\n",
    "socmed:media sosial\n",
    "btuh:butuh\n",
    "effort:upaya\n",
    "mn:mana\n",
    "byangin:wujud\n",
    "truck:mobil besar\n",
    "bnyk:banyak\n",
    "brng:barang\n",
    "udh:udah\n",
    "ddakan:dadakan\n",
    "bsa:bisa\n",
    "bgtu:gitu\n",
    "kdg:kadang\n",
    "kunaon:kenapa\n",
    "aya:ada\n",
    "naon:apa\n",
    "omong:ngomong\n",
    "full:penuh\n",
    "way:cara\n",
    "golden:emas\n",
    "galak:marah\n",
    "sien:takut\n",
    "can:belum\n",
    "aya:ada\n",
    "thr:tunjangan hari raya\n",
    "ajah:aja\n",
    "pildun:piala dunia\n",
    "ngatur:mengurus\n",
    "simbah:basah\n",
    "ngributin:meributkan\n",
    "ros:terus\n",
    "uda:udah\n",
    "tw:tahu\n",
    "prakompetisi:persaingan\n",
    "dtuntut:dituntut\n",
    "kickoff:mulai\n",
    "minim:sedikit\n",
    "mulu:terus\n",
    "support:dukung\n",
    "selip:meluangkan\n",
    "selebritis:terkenal\n",
    "fc:klub sepakbola\n",
    "star:mulai\n",
    "urg:saya\n",
    "nyata:asli\n",
    "representatif:tepat\n",
    "jigana:sepertinya\n",
    "moal:tidak\n",
    "laporke:laporin\n",
    "enggres:terbaik\n",
    "bwang:bang\n",
    "sengojo:sengaja\n",
    "mbantu:membantu\n",
    "ben:agar\n",
    "friendly match:pertandingan persahabatan\n",
    "gulir:mulai\n",
    "curiga:khawatir\n",
    "gaduh:rusuh\n",
    "salh:salah\n",
    "optimistis:percaya\n",
    "sanksi:hukuman\n",
    "kacau:hancur\n",
    "heran:bingung\n",
    "team:tim\n",
    "kena:sentuh\n",
    "embel:bawa\n",
    "for:untuk\n",
    "reporter:penyusun laporan\n",
    "kompetisi:persaingan\n",
    "hattrick:tiga gol\n",
    "udh:udah\n",
    "menarik:bagus\n",
    "kontra:lawan\n",
    "jokes:bercanda\n",
    "warkop:warung kopi\n",
    "mafia:kejahatan\n",
    "bbbrp:beberapa\n",
    "byk:banyak\n",
    "season:sesi\n",
    "noted:dicatat\n",
    "rancu:kacau\n",
    "usul:saran\n",
    "marquee player:pemain populer\n",
    "lobbaaaaaaaaaaaaaa:banyak\n",
    "schedulenya:jadwalnya\n",
    "gua:saya\n",
    "kaya:seperti\n",
    "regulasi:pengaturan\n",
    "sela:celah\n",
    "kaga:engga\n",
    "degradasi:kemunduran\n",
    "demen:suka\n",
    "seremonial:pembukaan\n",
    "penyerahan:memberikan\n",
    "pejabat:pegawai\n",
    "mejeng:diam\n",
    "sambut:menerima\n",
    "sempat:ada waktu\n",
    "duluuuu:dulu\n",
    "nyerahin:mempercayakan\n",
    "ceremonial:pembukaan\n",
    "overall:keseluruhan\n",
    "favorit:kesukaan\n",
    "kaga:engga\n",
    "ngeliat:melihat\n",
    "ttaaapi:tapi\n",
    "asa:tujuan\n",
    "mengbal:sepakbola\n",
    "teko:datang\n",
    "mundakno:naiknya\n",
    "nnak:ke\n",
    "kyok:seperti\n",
    "gaisok:engga bisa\n",
    "ketat:erat\n",
    "apresiasi:penghargaan\n",
    "dlam:dalam\n",
    "regulasi:peraturan\n",
    "rilis:resmi\n",
    "best:baik\n",
    "tlg:tolong\n",
    "mbakas:demi\n",
    "ono:ada\n",
    "ngarah:menuju\n",
    "entek:habis\n",
    "isine:isinya\n",

]

res = []
for i in slangwords_list:
    if i not in res:
        res.append(i)

res.sort()

f = open("daftar_slangwords.txt", "w")
f.writelines(res)
f.close()