"""Initial commit

Revision ID: dc46e7f4ee0d
Revises: 
Create Date: 2022-11-08 14:39:46.595922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc46e7f4ee0d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daftar_slangwords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kata_slang', sa.String(length=100), nullable=True),
    sa.Column('kata_baku', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daftar_stopwords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stopwords', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dataset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('raw_tweets', sa.Text(), nullable=True),
    sa.Column('clean_tweets', sa.Text(), nullable=True),
    sa.Column('label', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('dataset')
    op.drop_table('daftar_stopwords')
    op.drop_table('daftar_slangwords')
    # ### end Alembic commands ###
